# Generated by Django 4.2.7 on 2023-11-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='testimonials')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='application_status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_mode',
            field=models.CharField(choices=[('ONLINE', 'online'), ('BANK', 'bank')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('NOT_PAID', 'not_paid'), ('PAID', 'paid')], default='PENDING', max_length=20),
        ),
    ]
