# Generated by Django 4.2.7 on 2023-11-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_testimonial_alter_application_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='details',
            field=models.TextField(default=''),
        ),
    ]
