# Generated by Django 4.2.7 on 2023-11-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_imagecategory_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customcourserequest',
            old_name='course',
            new_name='message',
        ),
    ]
