# Generated by Django 4.2.7 on 2023-11-29 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_course_customcourserequest_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.application'),
        ),
    ]
