# Generated by Django 4.2.7 on 2023-12-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cohorts',
            field=models.ManyToManyField(blank=True, to='dashboard.cohort'),
        ),
    ]
