# Generated by Django 4.2.7 on 2023-12-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_course_cohorts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teachers',
        ),
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.CharField(default='GIMPA MAIN CAMPUS', max_length=100),
        ),
    ]
