# Generated by Django 4.2.7 on 2023-12-07 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_course_teachers_course_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.coursecategory'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='cohorts',
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(default='1 MONTH', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='cohorts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.cohort'),
        ),
    ]
