# Generated by Django 4.2.7 on 2023-12-07 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_course_category_remove_course_cohorts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cohorts',
            new_name='cohort',
        ),
    ]
