# Generated by Django 4.2.7 on 2023-12-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_rename_cohorts_course_cohort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcourserequest',
            name='message',
            field=models.TextField(),
        ),
    ]
