# Generated by Django 4.2.7 on 2023-12-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_course_allows_part_payment_course_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
