# Generated by Django 4.2.7 on 2023-12-21 08:23

from django.db import migrations, models

import dashboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_payment_network_alter_payment_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='application',
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default=dashboard.models.Payment.generate_transaction_id, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='application',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.application'),
        ),
    ]
