# Generated by Django 4.2.7 on 2023-12-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_remove_payment_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='application',
            field=models.ManyToManyField(to='dashboard.application'),
        ),
    ]
