# Generated by Django 4.2.7 on 2023-12-21 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_payment_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='application',
        ),
        migrations.AddField(
            model_name='payment',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.application'),
        ),
    ]
