# Generated by Django 4.2.7 on 2024-01-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_remove_payment_application_payment_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates'),
        ),
    ]
