# Generated by Django 4.2.7 on 2024-03-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_application_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fprice',
            field=models.IntegerField(default=0),
        ),
    ]
