# Generated by Django 4.2.7 on 2024-03-27 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_course_fprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='box_address',
            field=models.CharField(default='Accra - Ghana', max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='dob',
            field=models.DateField(default=datetime.date(2024, 3, 27)),
        ),
        migrations.AddField(
            model_name='application',
            name='box_address',
            field=models.CharField(default='Accra - Ghana', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='dob',
            field=models.DateField(default=datetime.date(2024, 3, 27)),
        ),
    ]
