# Generated by Django 4.2.7 on 2024-04-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_customcourserequest_is_replied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='residential_fees',
            field=models.IntegerField(default=0),
        ),
    ]
