# Generated by Django 4.2.7 on 2024-04-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_course_residential_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='coordinator_email',
            field=models.EmailField(default='trainingandconsulting@gimpa.edu.gh', max_length=254),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='coordinator_phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
