# Generated by Django 4.2.7 on 2025-07-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_course_fprice_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='precedence',
            field=models.IntegerField(default=0),
        ),
    ]
