from .applications import *
from .category import *
from .contact_messages import *
from .course_requests import *
from .courses import *
from .dashboard import *
from .facilitators import *
from .faqs import *
from .gallery import *
from .groups import *
from .notifications import *
from .payments import *
from .profile import *
from .settings import *
from .teams import *
from .testimonials import *
from .users import *
