# Generated by Django 4.2.7 on 2023-12-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_date_joined_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prefered_notification_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='prefered_notification_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
